### ISSUE TITLE
USGS Organization

### ISSUE THREAD

**Issue by mjperez-usgs** [usgs/seedscan#16]
I'm really sorry about posting this here. I literally could not find anywhere else to post this.
I'm part of USGS but I am unsure of how to join the github organization so everything USGS is under one umbrella. I've looked everywhere and nobody seems to have any info on how to manage our code or join (or contact) this account.

I know this isn't really relevant to this project, but it's under the USGS account.

**Comment by aringler-usgs** [comment]
Hello Michael,

You need to have an account with your email-usgs.  So mjperez-usgs.  You
then send an email to the USGS github group and they will add you
gs_github@usgs.gov.

Eric Martinez is one of the experts on this stuff so he can probably answer
your questions better than I can.

Best,
Adam

On Thu, May 21, 2015 at 1:06 PM, Michael Perez <notifications@github.com>
wrote:

> I'm really sorry about posting this here. I literally could not find
> anywhere else to post this.
> I'm part of USGS but I am unsure of how to join the github organization so
> everything USGS is under one umbrella. I've looked everywhere and nobody
> seems to have any info on how to manage our code or join (or contact) this
> account.
>
> I know this isn't really relevant to this project, but it's under the USGS
> account.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/usgs/seedscan/issues/16>.
>



-- 
Follow USGS Seismic Instrumentation on Twitter: @USGS_Seismic

**Comment by jholland-usgs** [comment]
I responded to your usgs email.

**Comment by mjperez-usgs** [comment]
Thanks, I got things going in the process.
